#!/usr/bin/env python3
"""X68 certifier keys for h=4 primitive norm gates.

X65 counts primitive X64 canonical chord-pair orbits in row-count currency.
X66 and X67 prove that the sparse-resultant prime set is constant under the
larger relation generated by X64 chord transforms and Galois unit scaling.

This verifier packages that relation into a canonical certifier key.  The key
is for resultant computation only; any surviving obstruction must still be
expanded in the X65 row-count currency.
"""

from __future__ import annotations

from collections import Counter, defaultdict
import json
import math
import os
import sys
from typing import Any

import verify_h1_u1_toy_harness as h1
import verify_x64_h4_linear_orbit_compression as x64


HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
CERT = os.path.join(
    REPO,
    "experimental",
    "data",
    "certificates",
    "x68-h4-norm-gate-certifier-keys",
    "x68_h4_norm_gate_certifier_keys.json",
)
DAG = os.path.join(REPO, "experimental", "data", "prize-dag", "prize_dag.json")
X60_CERT = os.path.join(
    REPO,
    "experimental",
    "data",
    "certificates",
    "x60-h4-linear-triple-form",
    "x60_h4_linear_triple_form.json",
)
X65_CERT = os.path.join(
    REPO,
    "experimental",
    "data",
    "certificates",
    "x65-h4-linear-orbit-budget",
    "x65_h4_linear_orbit_budget.json",
)

FAILS: list[str] = []
NCHECK = 0


def check(name: str, cond: bool, detail: str = "") -> None:
    global NCHECK
    NCHECK += 1
    tag = "PASS" if cond else "FAIL"
    line = f"[{tag}] {name}"
    if detail:
        line += f"   ({detail})"
    print(line, flush=True)
    if not cond:
        FAILS.append(name)


def load_json(path: str) -> Any:
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def check_dependency_nodes() -> dict[str, str]:
    dag = load_json(DAG)
    statuses = {node["id"]: node["status"] for node in dag["nodes"]}
    needed = {
        "x64_h4_linear_orbit_compression": "PROVED",
        "x65_h4_linear_orbit_budget": "PROVED",
        "x66_h4_norm_gate_orbit_invariance": "PROVED",
        "x67_h4_galois_norm_gate_compression": "PROVED",
        "active_core_count_bound": "TARGET",
    }
    for node, expected in needed.items():
        actual = statuses.get(node, "missing")
        check(f"DAG node {node} has expected status", actual == expected, actual)
    return {node: statuses.get(node, "missing") for node in needed}


def units_mod(n: int) -> list[int]:
    return [u for u in range(n) if math.gcd(u, n) == 1]


def unit_scale(n: int, triple: tuple[int, int, int], u: int) -> tuple[int, int, int]:
    return tuple((u * value) % n for value in triple)


def certifier_raw_orbit(n: int, triple: tuple[int, int, int]) -> set[tuple[int, int, int]]:
    orbit: set[tuple[int, int, int]] = set()
    for u in units_mod(n):
        orbit.update(x64.transforms(n, unit_scale(n, triple, u)))
    return orbit


def certifier_key(n: int, triple: tuple[int, int, int]) -> tuple[int, int, int]:
    return min(certifier_raw_orbit(n, triple))


def replay_primitive_x64_reps(row: dict[str, Any]) -> set[tuple[int, int, int]]:
    n = int(row["n"])
    p = int(row["p"])
    domain = h1.mu_domain(p, n)
    exponent_by_value = {value: exp for exp, value in enumerate(domain)}

    reps: set[tuple[int, int, int]] = set()
    for a, x in enumerate(domain):
        for b, y in enumerate(domain):
            z = (x + y - 1) % p
            c = exponent_by_value.get(z)
            if c is None or not x64.is_filtered(n, a, b, c):
                continue
            triple = (a, b, c)
            if x64.content(n, triple) == 1:
                reps.add(x64.canonical(triple, n))
    return reps


def row_report(row: dict[str, Any], x65_row: dict[str, Any]) -> dict[str, Any]:
    n = int(row["n"])
    reps = replay_primitive_x64_reps(row)
    expected_reps = int(x65_row["primitive_canonical_orbit_count"])
    check(
        f"{row['label']}: primitive X64 reps match X65",
        len(reps) == expected_reps,
        f"computed={len(reps)}, X65={expected_reps}",
    )

    classes: dict[tuple[int, int, int], list[tuple[int, int, int]]] = defaultdict(list)
    key_failures: list[dict[str, Any]] = []
    raw_orbit_failures: list[dict[str, Any]] = []
    raw_orbit_sizes: list[int] = []
    raw_orbit_intersections: list[int] = []

    for rep in sorted(reps):
        key = certifier_key(n, rep)
        classes[key].append(rep)
        if certifier_key(n, key) != key and len(key_failures) < 5:
            key_failures.append({"rep": list(rep), "key": list(key), "kind": "not_idempotent"})
        if not x64.is_filtered(n, *key) and len(key_failures) < 5:
            key_failures.append({"rep": list(rep), "key": list(key), "kind": "key_not_filtered"})
        if x64.content(n, key) != 1 and len(key_failures) < 5:
            key_failures.append({"rep": list(rep), "key": list(key), "kind": "key_not_primitive"})

        raw = certifier_raw_orbit(n, rep)
        raw_orbit_sizes.append(len(raw))
        raw_orbit_intersections.append(len(raw & reps))
        for member in raw:
            if certifier_key(n, member) != key and len(raw_orbit_failures) < 5:
                raw_orbit_failures.append(
                    {"rep": list(rep), "member": list(member), "key": list(key)}
                )
            if (not x64.is_filtered(n, *member) or x64.content(n, member) != 1) and len(raw_orbit_failures) < 5:
                raw_orbit_failures.append(
                    {"rep": list(rep), "member": list(member), "kind": "raw_member_bad"}
                )

    check(
        f"{row['label']}: certifier keys are filtered primitive and idempotent",
        not key_failures,
        f"sample_failures={key_failures}",
    )
    check(
        f"{row['label']}: raw certifier orbits have one key",
        not raw_orbit_failures,
        f"sample_failures={raw_orbit_failures}",
    )
    check(
        f"{row['label']}: certifier classes partition primitive X64 reps",
        sum(len(items) for items in classes.values()) == len(reps),
        f"classes={len(classes)}, reps={len(reps)}",
    )
    check(
        f"{row['label']}: certifier class count is no larger than X65 row reps",
        len(classes) <= len(reps),
        f"classes={len(classes)}, reps={len(reps)}",
    )

    class_size_hist = Counter(len(items) for items in classes.values())
    raw_size_hist = Counter(raw_orbit_sizes)
    intersection_hist = Counter(raw_orbit_intersections)
    sample_classes = [
        {"key": list(key), "row_representatives": [list(rep) for rep in sorted(items)[:5]]}
        for key, items in sorted(classes.items())[:5]
    ]

    return {
        "label": row["label"],
        "kind": row["kind"],
        "n": n,
        "p": int(row["p"]),
        "primitive_x64_representatives": len(reps),
        "certifier_key_count": len(classes),
        "row_representatives_merged": len(reps) - len(classes),
        "certifier_class_size_histogram_on_row_reps": {
            str(k): v for k, v in sorted(class_size_hist.items())
        },
        "raw_certifier_orbit_size_histogram": {str(k): v for k, v in sorted(raw_size_hist.items())},
        "row_rep_intersection_histogram_per_raw_certifier_orbit": {
            str(k): v for k, v in sorted(intersection_hist.items())
        },
        "sample_certifier_classes": sample_classes,
        "key_failures": key_failures,
        "raw_orbit_failures": raw_orbit_failures,
    }


def by_label(rows: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    return {row["label"]: row for row in rows}


def build_certificate() -> dict[str, Any]:
    deps = check_dependency_nodes()
    x60 = load_json(X60_CERT)
    x65 = load_json(X65_CERT)
    check("X60 certificate has replay rows", bool(x60.get("rows")))
    check("X65 certificate has replay rows", bool(x65.get("rows")))

    x65_rows = by_label(x65["rows"])
    rows = []
    for row in x60["rows"]:
        label = row["label"]
        check(f"{label}: X65 row exists", label in x65_rows)
        rows.append(row_report(row, x65_rows[label]))

    check(
        "all replay rows have valid certifier keys",
        all(not row["key_failures"] and not row["raw_orbit_failures"] for row in rows),
    )
    check(
        "some replay row has a nontrivial key merge",
        any(row["row_representatives_merged"] > 0 for row in rows),
    )
    check(
        "certifier key counts never exceed row-count representatives",
        all(row["certifier_key_count"] <= row["primitive_x64_representatives"] for row in rows),
    )

    return {
        "task": "X68 h=4 norm-gate certifier keys",
        "node": "active_core_count_bound",
        "status": "PROVED CERTIFIER KEY: CHORD AND GALOIS ACTIONS SHARE RESULTANT PRIME SETS",
        "theorem": (
            "Define K(a,b,c) as the lexicographically least word in the orbit "
            "generated by X64 chord transforms and unit exponent scaling.  "
            "X66 and X67 imply every word with the same key has the same "
            "cyclotomic resultant prime set.  The key is filtered and "
            "content-one whenever the input is.  This packages resultant "
            "computation; finite-row survivor mass must still be expanded "
            "using X65 primitive X64 representative counts."
        ),
        "warning": (
            "The raw certifier orbit contains many exponent words that are not "
            "solutions for the fixed finite-field generator.  The key compresses "
            "resultant computation only, not row-count mass."
        ),
        "dependency_statuses": deps,
        "rows": rows,
        "checks": NCHECK,
    }


def main() -> int:
    write = "--write-certificate" in sys.argv
    cert = build_certificate()
    if write:
        os.makedirs(os.path.dirname(CERT), exist_ok=True)
        with open(CERT, "w", encoding="utf-8") as fh:
            json.dump(cert, fh, indent=2, sort_keys=True)
            fh.write("\n")
        print(f"[write] {CERT}")

    expected = None
    if os.path.exists(CERT):
        expected = load_json(CERT)
    check("certificate exists", expected is not None, CERT)
    if expected is not None:
        check("certificate matches recomputed summary", cert == expected)

    print("\nnorm-gate certifier-key rows:")
    for row in cert["rows"]:
        print(
            f"{row['label']}: x64_reps={row['primitive_x64_representatives']} "
            f"certifier_keys={row['certifier_key_count']} "
            f"merged={row['row_representatives_merged']}"
        )

    if FAILS:
        print("\nFAIL:")
        for name in FAILS:
            print(f"  - {name}")
        return 1

    print(f"\nPASS: {NCHECK} X68 h4 norm-gate certifier-key checks")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
